### ISSUE TITLE
Panel and List view showing large amounts of blank printers  - error when using filter

### ISSUE THREAD

**Issue by wicada** [OctoFarm/OctoFarm#1197]
### OctoFarm Version

1.6.6

### OctoPrint Version(s)

1.8.2

### pm2 or docker?

pm2

### Operating System

Ubuntu

### Location of the problem

Web Interface

### Description of the problem

```markdown
When viewing the list and Panel I am getting a bunch of blank "Loading..." printers in between the actual printers. When using the filter State:Active I receive this error message.

 
TypeError
×

TypeError ERROR (undefined):
Please report this error to OctoFarm Issues!
Cannot read properties of null (reading 'id')
FILE INFO
LINE: undefined
COL: undefined
STACK:
TypeError: Cannot read properties of null (reading 'id') at Ft (http://192.168.84.56:4000/assets/dist/list-view.runner.1.6.6.min.js:2:87461) at http://192.168.84.56:4000/assets/dist/list-view.runner.1.6.6.min.js:2:240435 at async gi (http://192.168.84.56:4000/assets/dist/list-view.runner.1.6.6.min.js:2:237844) at async http://192.168.84.56:4000/assets/dist/list-view.runner.1.6.6.min.js:2:241648
```

### Steps taken to reproduce

Clicked Panel on Top Bar
Clicked List on Top Bar

### What did you expect to happen

All my printers to be listed correctly.

### To avoid the problem I had to

Not use Panel and List views

**Comment by wicada** [comment]
![list view2](https://user-images.githubusercontent.com/10208936/188882426-2fbf31d0-238d-42f3-9029-45cd498881a1.png)
![list view](https://user-images.githubusercontent.com/10208936/188882429-20fdca3f-dc64-4ed6-a65f-4c8a0a98a0b1.png)
![printers2](https://user-images.githubusercontent.com/10208936/188882430-4a1d845e-4c8f-471b-a436-b9da69e82a83.png)
![printers1](https://user-images.githubusercontent.com/10208936/188882431-81d89475-71e5-4b57-9786-2dd11406430e.png)

**Comment by wicada** [comment]
Just realized this issue was already posted
