### ISSUE TITLE
Docker webpage octofarm not accessible after creation 

### ISSUE THREAD

**Issue by Doprintityourself** [OctoFarm/OctoFarm#1380]
### OctoFarm Version

latest

### OctoPrint Version(s)

latest

### pm2 or docker?

pm2

### Operating System

Linux Docker

### Description of the problem

after composing a stack in Portainer both containers are working but website of Octofarm ist not reachable on port 4000
Attached the log file of the Octofarm container there are errors
As I am not a Programmer I cannot understand or fix

Thanks for having a look

### Steps taken to reproduce

just  composed the script provided on the Octofarm docker dokumentation replaced admin an password as required:

version: '3.4' 

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mypw
      MONGO_INITDB_DATABASE: octofarm
    volumes:
    # Local volume (change to mongodb-data for a named volume folder)
      - ./mongodb-data:/data/db
    restart: unless-stopped

  octofarm:
    container_name: octofarm
    # choose octofarm/octofarm:latest
    image: octofarm/octofarm:latest
    restart: unless-stopped
    links:
      - mongodb
    ports:
      - 4000:4000 # port of SYSTEM : port of CONTAINER
    environment:
      - MONGO=mongodb://admin:mypw@mongodb:27017/octofarm?authSource=admin
    volumes:
    # Volumes as local relative folders (validate with 'docker-compose config')
      - ./OctoFarm/logs:/app/logs
      - ./OctoFarm/scripts:/app/scripts
      - ./OctoFarm/images:/app/images
log: 
👍 2023-01-31T09:29:20.424987161Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20: 1/31/23, 9:29:20 AM | INFO | Server-Env  
2023-01-31T09:29:20.425000988Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:  INFO MESSAGE: ✓ Running OctoFarm version 1.7.3 in non-NPM mode! 
2023-01-31T09:29:20.425360067Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20: 1/31/23, 9:29:20 AM | INFO | Server-Env  
2023-01-31T09:29:20.425400293Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:  INFO MESSAGE: ✓ MONGO environment variable set! 
2023-01-31T09:29:20.425884969Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20: 1/31/23, 9:29:20 AM | WARN | Server-Env  
2023-01-31T09:29:20.425921103Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:  WARN MESSAGE: ~ The OCTOFARM_PORT setting was not a correct port number: >= 0 and < 65536. Actual value: undefined. 
2023-01-31T09:29:20.426628673Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20: 1/31/23, 9:29:20 AM | ERROR | Utils-Env  
2023-01-31T09:29:20.426640941Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:  ERROR MESSAGE: cant find target folder... | /app/images
2023-01-31T09:29:20.431216177Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20: Error: EACCES: permission denied, open '../images/bg.jpg'
2023-01-31T09:29:20.431244774Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Object.openSync (fs.js:498:3)
2023-01-31T09:29:20.431277307Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Object.writeFileSync (fs.js:1529:35)
2023-01-31T09:29:20.431310969Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Object.ensureBackgroundImageExists (/app/server/utils/env.utils.js:112:8)
2023-01-31T09:29:20.431341711Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at setupEnvConfig (/app/server/app-env.js:282:12)
2023-01-31T09:29:20.431367100Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Object.<anonymous> (/app/server/app.js:27:3)
2023-01-31T09:29:20.431373058Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2023-01-31T09:29:20.431393053Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2023-01-31T09:29:20.431401648Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Module.load (internal/modules/cjs/loader.js:950:32)
2023-01-31T09:29:20.431441383Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2023-01-31T09:29:20.431445909Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23) {
2023-01-31T09:29:20.431469561Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:   errno: -13,
2023-01-31T09:29:20.431506442Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:   syscall: 'open',
2023-01-31T09:29:20.431511468Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:   code: 'EACCES',
2023-01-31T09:29:20.431529422Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20:   path: '../images/bg.jpg'
2023-01-31T09:29:20.431552347Z 09:29:20 0|OctoFarm  | 2023-01-31T09:29:20: }
2023-01-31T09:29:20.437724013Z 2023-01-31T09:29:20: PM2 log: App [OctoFarm:0] exited with code [1] via signal [SIGINT]
2023-01-31T09:29:20.438092613Z 2023-01-31T09:29:20: PM2 log: App [OctoFarm:0] will restart in 15000ms
2023-01-31T09:29:20.438355955Z 09:29:20 PM2         | App [OctoFarm:0] exited with code [1] via signal [SIGINT]
2023-01-31T09:29:20.438500642Z 09:29:20 PM2         | App [OctoFarm:0] will restart in 15000ms
2023-01-31T09:29:35.443324031Z 2023-01-31T09:29:35: PM2 log: App [OctoFarm:0] starting in -fork mode-
2023-01-31T09:29:35.444139434Z 09:29:35 PM2         | App [OctoFarm:0] starting in -fork mode-
2023-01-31T09:29:35.456471124Z 2023-01-31T09:29:35: PM2 log: App [OctoFarm:0] online
2023-01-31T09:29:35.457189741Z 09:29:35 PM2         | App [OctoFarm:0] online
2023-01-31T09:29:36.198851045Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: 1/31/23, 9:29:36 AM | INFO | Server-Env  
2023-01-31T09:29:36.198877426Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:  INFO MESSAGE: ✓ Parsed environment and (optional) .env file 
2023-01-31T09:29:36.199822441Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: 1/31/23, 9:29:36 AM | INFO | Server-Env  
2023-01-31T09:29:36.199838211Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:  INFO MESSAGE: ✓ NODE_ENV variable correctly set (production)! 
2023-01-31T09:29:36.201329060Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: 1/31/23, 9:29:36 AM | INFO | Server-Env  
2023-01-31T09:29:36.201393043Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:  INFO MESSAGE: ✓ Running OctoFarm version 1.7.3 in non-NPM mode! 
2023-01-31T09:29:36.201688118Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: 1/31/23, 9:29:36 AM | INFO | Server-Env  
2023-01-31T09:29:36.201695295Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:  INFO MESSAGE: ✓ MONGO environment variable set! 
2023-01-31T09:29:36.202157201Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: 1/31/23, 9:29:36 AM | WARN | Server-Env  
2023-01-31T09:29:36.202169475Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:  WARN MESSAGE: ~ The OCTOFARM_PORT setting was not a correct port number: >= 0 and < 65536. Actual value: undefined. 
2023-01-31T09:29:36.202787735Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: 1/31/23, 9:29:36 AM | ERROR | Utils-Env  
2023-01-31T09:29:36.202805781Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:  ERROR MESSAGE: cant find target folder... | /app/images
2023-01-31T09:29:36.207728897Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: Error: EACCES: permission denied, open '../images/bg.jpg'
2023-01-31T09:29:36.207741862Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Object.openSync (fs.js:498:3)
2023-01-31T09:29:36.207794655Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Object.writeFileSync (fs.js:1529:35)
2023-01-31T09:29:36.207806403Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Object.ensureBackgroundImageExists (/app/server/utils/env.utils.js:112:8)
2023-01-31T09:29:36.207810176Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at setupEnvConfig (/app/server/app-env.js:282:12)
2023-01-31T09:29:36.207813455Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Object.<anonymous> (/app/server/app.js:27:3)
2023-01-31T09:29:36.207821254Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2023-01-31T09:29:36.207842477Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2023-01-31T09:29:36.207884883Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Module.load (internal/modules/cjs/loader.js:950:32)
2023-01-31T09:29:36.207890705Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2023-01-31T09:29:36.207909469Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23) {
2023-01-31T09:29:36.207949159Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:   errno: -13,
2023-01-31T09:29:36.207953751Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:   syscall: 'open',
2023-01-31T09:29:36.207982390Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:   code: 'EACCES',
2023-01-31T09:29:36.207993734Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36:   path: '../images/bg.jpg'
2023-01-31T09:29:36.208009468Z 09:29:36 0|OctoFarm  | 2023-01-31T09:29:36: }
2023-01-31T09:29:36.213865577Z 2023-01-31T09:29:36: PM2 log: App [OctoFarm:0] exited with code [1] via signal [SIGINT]
2023-01-31T09:29:36.214247543Z 2023-01-31T09:29:36: PM2 log: App [OctoFarm:0] will restart in 15000ms
2023-01-31T09:29:36.214477821Z 09:29:36 PM2         | App [OctoFarm:0] exited with code [1] via signal [SIGINT]
2023-01-31T09:29:36.214581599Z 09:29:36 PM2         | App [OctoFarm:0] will restart in 15000ms
2023-01-31T09:29:51.224418336Z 2023-01-31T09:29:51: PM2 log: App [OctoFarm:0] starting in -fork mode-
2023-01-31T09:29:51.225203885Z 09:29:51 PM2         | App [OctoFarm:0] starting in -fork mode-
2023-01-31T09:29:51.235844743Z 2023-01-31T09:29:51: PM2 log: App [OctoFarm:0] online
2023-01-31T09:29:51.236640706Z 09:29:51 PM2         | App [OctoFarm:0] online
2023-01-31T09:29:51.998866059Z 09:29:51 0|OctoFarm  | 2023-01-31T09:29:51: 1/31/23, 9:29:51 AM | INFO | Server-Env  
2023-01-31T09:29:51.998885014Z 09:29:51 0|OctoFarm  | 2023-01-31T09:29:51:  INFO MESSAGE: ✓ Parsed environment and (optional) .env file 
2023-01-31T09:29:51.999821020Z 09:29:51 0|OctoFarm  | 2023-01-31T09:29:51: 1/31/23, 9:29:51 AM | INFO | Server-Env  
2023-01-31T09:29:51.999836415Z 09:29:51 0|OctoFarm  | 2023-01-31T09:29:51:  INFO MESSAGE: ✓ NODE_ENV variable correctly set (production)! 
2023-01-31T09:29:52.001474890Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52: 1/31/23, 9:29:52 AM | INFO | Server-Env  
2023-01-31T09:29:52.001493505Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:  INFO MESSAGE: ✓ Running OctoFarm version 1.7.3 in non-NPM mode! 
2023-01-31T09:29:52.001774976Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52: 1/31/23, 9:29:52 AM | INFO | Server-Env  
2023-01-31T09:29:52.001824112Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:  INFO MESSAGE: ✓ MONGO environment variable set! 
2023-01-31T09:29:52.002258893Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52: 1/31/23, 9:29:52 AM | WARN | Server-Env  
2023-01-31T09:29:52.002299736Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:  WARN MESSAGE: ~ The OCTOFARM_PORT setting was not a correct port number: >= 0 and < 65536. Actual value: undefined. 
2023-01-31T09:29:52.002996078Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52: 1/31/23, 9:29:52 AM | ERROR | Utils-Env  
2023-01-31T09:29:52.003050154Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:  ERROR MESSAGE: cant find target folder... | /app/images
2023-01-31T09:29:52.007816418Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52: Error: EACCES: permission denied, open '../images/bg.jpg'
2023-01-31T09:29:52.007863303Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Object.openSync (fs.js:498:3)
2023-01-31T09:29:52.007884924Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Object.writeFileSync (fs.js:1529:35)
2023-01-31T09:29:52.007889173Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Object.ensureBackgroundImageExists (/app/server/utils/env.utils.js:112:8)
2023-01-31T09:29:52.007893670Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at setupEnvConfig (/app/server/app-env.js:282:12)
2023-01-31T09:29:52.007903638Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Object.<anonymous> (/app/server/app.js:27:3)
2023-01-31T09:29:52.007938181Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2023-01-31T09:29:52.007942886Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2023-01-31T09:29:52.007956072Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Module.load (internal/modules/cjs/loader.js:950:32)
2023-01-31T09:29:52.007979026Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2023-01-31T09:29:52.007997402Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23) {
2023-01-31T09:29:52.008021570Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:   errno: -13,
2023-01-31T09:29:52.008060760Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:   syscall: 'open',
2023-01-31T09:29:52.008065696Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:   code: 'EACCES',
2023-01-31T09:29:52.008084744Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52:   path: '../images/bg.jpg'
2023-01-31T09:29:52.008102109Z 09:29:52 0|OctoFarm  | 2023-01-31T09:29:52: }
2023-01-31T09:29:52.013813746Z 2023-01-31T09:29:52: PM2 log: App [OctoFarm:0] exited with code [1] via signal [SIGINT]
2023-01-31T09:29:52.014134044Z 2023-01-31T09:29:52: PM2 log: App [OctoFarm:0] will restart in 15000ms
2023-01-31T09:29:52.014381004Z 09:29:52 PM2         | App [OctoFarm:0] exited with code [1] via signal [SIGINT]
2023-01-31T09:29:52.014565974Z 09:29:52 PM2         | App [OctoFarm:0] will restart in 15000ms

**Comment by NotExpectedYet** [comment]
It's a permissions issue, you'll need to `sudo chmod 777 -R octofarm/` or whatever your octofarm directory is. 

I'm planning to fix the docker to make this not required but I'm half way through moving house currently and don't have access to a PC

**Comment by Doprintityourself** [comment]
sorry to ask but may be you can help
how do I access octofarm container seems not working: 
1. docker exec -it octofarm /bin/bash is not working  either in cli nore in portainer
2. Is there a password to access the container

**Comment by NotExpectedYet** [comment]
> sorry to ask but may be you can help how do I access octofarm container seems not working:
> 
> 1. docker exec -it octofarm /bin/bash is not working  either in cli nore in portainer
> 2. Is there a password to access the container

it's outside the container, on your host. I assume is Linux?

**Comment by Doprintityourself** [comment]
As I created it inside portainer I assume it is residing inside a docker container and not on the filesystem. Both mogdb and octofarm are in containers!  
find -name octofarm or Octofarm, does not give any results on the linux filesystem. 
So isen't it created in the octofarm container/encrypted?
I am not familiar what a container does or is or if there inside is the octofarm directory structure.

**Comment by NotExpectedYet** [comment]
And what system is portainer installed on? 

Dockers are finite so they require access to the local file system. You've defined mount paths above as `./OctoFarm/**` that path need permissions changing for it to work.

**Comment by NotExpectedYet** [comment]
I recommend you do a bit more reading about dockers and how they work. It will help a lot with troubleshooting steps.

**Comment by Doprintityourself** [comment]
I composed it by hand again on cli and set the permissions
I can reach the Octofarm url now and as it seems it now hast created real octofarm directory that I have given rights.

Obviously something different happend or I should say not happend during the stack creation with the same script.
It seems to build the mogo_db and the octofarm container but not the real structure via downlaod a suppose.
Thanks inspite of that for your support
have nice day
