### ISSUE TITLE
Error installing/running OctoFarm

### ISSUE THREAD

**Issue by gray013** [OctoFarm/OctoFarm#238]
Hi, really great project!

I'm going through the install process for Ubuntu, currently running Ubuntu 20.04 on a pi 3B+ if that's relevant, and when I get to step 8 on your instructions, npm start, the following error message comes out:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/gary/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/gary/package.json                 '
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

If I try to access OctoFarm through the web portal the following comes up:

Error: Failed to lookup view "database" in views directory "/home/gary/OctoFarm/views"
    at Function.render (/home/gary/OctoFarm/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/home/gary/OctoFarm/node_modules/express/lib/response.js:1012:7)
    at ServerResponse.res.render (/home/gary/OctoFarm/node_modules/express-ejs-layouts/lib/express-layouts.js:77:18)
    at /home/gary/OctoFarm/server_src/routes/databaseIssue.js:5:7
    at Layer.handle [as handle_request] (/home/gary/OctoFarm/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gary/OctoFarm/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/gary/OctoFarm/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/gary/OctoFarm/node_modules/express/lib/router/layer.js:95:5)
    at /home/gary/OctoFarm/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/gary/OctoFarm/node_modules/express/lib/router/index.js:335:12)
    at next (/home/gary/OctoFarm/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/gary/OctoFarm/node_modules/express/lib/router/index.js:174:3)
    at router (/home/gary/OctoFarm/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/gary/OctoFarm/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/gary/OctoFarm/node_modules/express/lib/router/index.js:317:13)
    at /home/gary/OctoFarm/node_modules/express/lib/router/index.js:284:7

**Comment by NotExpectedYet** [comment]
You missed this step
![image](https://user-images.githubusercontent.com/61137988/106567247-6f483600-6529-11eb-92da-cb936c4dda9a.png)

**Comment by NotExpectedYet** [comment]
Looking at your output I would clear out your home folder and start again as you've some how done some in the OctoFarm directory and some in the user Gary's home directory.

**Comment by davidzwa** [comment]
@gray013 in order to help you out we need more information. Please be so kind to get back to us.

**Comment by davidzwa** [comment]
Related to #365
