### ISSUE TITLE
MongoDB Error saving farmPrinter in `trackCounters` after printer creation

### ISSUE THREAD

**Issue by davidzwa** [OctoFarm/OctoFarm#624]
### Description of the problem

A mongoose/mongodb error is thrown in the `state.js:trackCounters` function stating that no matching ID was found for the document. So we're trying to update something that is not saved yet.
The error log is repeated every 30 secs.

```bash
Exception data:
{
  "version": 0,
  "modifiedPaths": [
    "sortIndex",
    "dateAdded",
    "powerSettings",
    "currentActive",
    "currentOffline",
    "selectedFilament",
    "tempTriggers",
    "feedRate",
    "flowRate",
    "costSettings",
    "currentUser",
    "camURL",
    "storage",
    "fileList",
    "octoPrintVersion",
    "currentIdle"
  ]
}

Error message:
"No matching document found for id \"60c1c466fe6f2f4b1cc2fc37\" version 0 modifiedPaths \"sortIndex, dateAdded, powerSettings, currentActive, currentOffline, selectedFilament, tempTriggers, feedRate, flowRate, costSettings, currentUser, camURL, storage, fileList, octoPrintVersion, currentIdle\""

Stack trace:
VersionError: No matching document found for id "60c1c466fe6f2f4b1cc2fc37" version 0 modifiedPaths "sortIndex, dateAdded, powerSettings, currentActive, currentOffline, selectedFilament, tempTriggers, feedRate, flowRate, costSettings, currentUser, camURL, storage, fileList, octoPrintVersion, currentIdle"
    at generateVersionError (C:\Users\david\Projects\WebstormProjects\OctoFarm\node_modules\mongoose\lib\model.js:432:10)
    at model.Model.save (C:\Users\david\Projects\WebstormProjects\OctoFarm\node_modules\mongoose\lib\model.js:488:28)
    at Function.trackCounters (C:\Users\david\Projects\WebstormProjects\OctoFarm\server_src\runners\state.js:1848:12)
    at Timeout._onTimeout (C:\Users\david\Projects\WebstormProjects\OctoFarm\server_src\runners\state.js:57:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

### Reproduction of the problem

```bash
- Add a printer
- See error in logs
```

**Comment by davidzwa** [comment]
Resyncing the printer didnt fix it. Restarting the server fixed it.
